# Profile information
name: Prozaicznie 
title: Tak mi dopomóż book
#description:  # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://tmbook.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: takmidopomozbook/ #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: #Add your Github

# Contact form
#email: #your-email@domain.com

# Comments
#discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
